"""Add performance indexes

Revision ID: 2bd3043d53d6
Revises: fb49bd4fcf0b
Create Date: 2026-02-11 10:44:20.294188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd3043d53d6'
down_revision = 'fb49bd4fcf0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_activities', schema=None) as batch_op:
        # batch_op.drop_constraint(batch_op.f('student_activities_verification_token_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_student_activities_activity_type_id'), ['activity_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_activities_certificate_hash'), ['certificate_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_activities_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_activities_student_id'), ['student_id'], unique=False)
        # batch_op.create_index(batch_op.f('ix_student_activities_verification_token'), ['verification_token'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        pass
        # batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        # batch_op.drop_constraint(batch_op.f('users_institution_id_key'), type_='unique')
        # batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        # batch_op.create_index(batch_op.f('ix_users_institution_id'), ['institution_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_institution_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_institution_id_key'), ['institution_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('student_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_activities_verification_token'))
        batch_op.drop_index(batch_op.f('ix_student_activities_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_activities_status'))
        batch_op.drop_index(batch_op.f('ix_student_activities_certificate_hash'))
        batch_op.drop_index(batch_op.f('ix_student_activities_activity_type_id'))
        batch_op.create_unique_constraint(batch_op.f('student_activities_verification_token_key'), ['verification_token'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
